# Generated by Django 5.1.4 on 2025-02-18 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
    ]
